# Import dataset

In [2]:
import pandas as pd

df = pd.read_csv('/kaggle/input/datasets/prasad22/healthcare-dataset/healthcare_dataset.csv')
df.head()

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
0,Bobby JacksOn,30,Male,B-,Cancer,2024-01-31,Matthew Smith,Sons and Miller,Blue Cross,18856.281306,328,Urgent,2024-02-02,Paracetamol,Normal
1,LesLie TErRy,62,Male,A+,Obesity,2019-08-20,Samantha Davies,Kim Inc,Medicare,33643.327287,265,Emergency,2019-08-26,Ibuprofen,Inconclusive
2,DaNnY sMitH,76,Female,A-,Obesity,2022-09-22,Tiffany Mitchell,Cook PLC,Aetna,27955.096079,205,Emergency,2022-10-07,Aspirin,Normal
3,andrEw waTtS,28,Female,O+,Diabetes,2020-11-18,Kevin Wells,"Hernandez Rogers and Vang,",Medicare,37909.782410,450,Elective,2020-12-18,Ibuprofen,Abnormal
4,adrIENNE bEll,43,Female,AB+,Cancer,2022-09-19,Kathleen Hanna,White-White,Aetna,14238.317814,458,Urgent,2022-10-09,Penicillin,Abnormal

# Data Processing & Cleaning

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 55500 entries, 0 to 55499
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Name                55500 non-null  object
 1   Age                 55500 non-null  int64
 2   Gender              55500 non-null  object
 3   Blood Type          55500 non-null  object
 4   Medical Condition   55500 non-null  object
 5   Date of Admission   55500 non-null  object
 6   Doctor              55500 non-null  object
 7   Hospital            55500 non-null  object
 8   Insurance Provider  55500 non-null  object
 9   Billing Amount      55500 non-null  float64
 10  Room Number         55500 non-null  int64
 11  Admission Type      55500 non-null  object
 12  Discharge Date      55500 non-null  object
 13  Medication          55500 non-null  object
 14  Test Results        55500 non-null  object
dtypes: float64(1), int64(2), object(12)
memory usage: 6.4+ MB

Perintah **df.info()** merupakan perintah untuk mengecek Informasi dari dataset 

Informasi dataset terdapat total 55.500 data pasien yang tersedia, terdapat 15 total column

In [4]:
df.isnull().sum()

Name                  0
Age                   0
Gender                0
Blood Type            0
Medical Condition     0
Date of Admission     0
Doctor                0
Hospital              0
Insurance Provider    0
Billing Amount        0
Room Number           0
Admission Type        0
Discharge Date        0
Medication            0
Test Results          0
dtype: int64

Perintah **df.isnull()** merupakan perintah untuk mengecek apa ada terdapat **missing value**, dan sambungan **.sum()** merupakan perintah untuk menghitung total

dari Informasi diatas tidak terdapat missing value pada setiap kolom dataset

In [5]:
df.duplicated().sum()

np.int64(534)

Perintah **df.duplicated().sum()** merupakan perintah untuk mengecek setiap baris apakah ada data yang terduplikasi (mirip)

In [6]:
df['Name'] = df['Name'].str.strip().str.title()

Perintah **df['Name'].str.strip().str.title()** merupakan perintah memperbaiki tulisan nama pada dataset

In [7]:
df['Gender'].value_counts()

Gender
Male      27774
Female    27726
Name: count, dtype: int64

Perintah **df['Gender'].value_counts()** merupakan perintah untuk menghitung berapa banyak pasien perempuan dan pasien laki-laki

In [8]:
df = df.drop_duplicates()

Perintah **df.drop_duplicates()** merupakan perintah untuk menghapus duplicate dari dataset

In [9]:
df.duplicated().sum()

np.int64(0)

# Analysis (EDA)

In [10]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df.head()

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
0,Bobby Jackson,30,Male,B-,Cancer,2024-01-31,Matthew Smith,Sons and Miller,Blue Cross,18856.281306,328,Urgent,2024-02-02,Paracetamol,Normal
1,Leslie Terry,62,Male,A+,Obesity,2019-08-20,Samantha Davies,Kim Inc,Medicare,33643.327287,265,Emergency,2019-08-26,Ibuprofen,Inconclusive
2,Danny Smith,76,Female,A-,Obesity,2022-09-22,Tiffany Mitchell,Cook PLC,Aetna,27955.096079,205,Emergency,2022-10-07,Aspirin,Normal
3,Andrew Watts,28,Female,O+,Diabetes,2020-11-18,Kevin Wells,"Hernandez Rogers and Vang,",Medicare,37909.782410,450,Elective,2020-12-18,Ibuprofen,Abnormal
4,Adrienne Bell,43,Female,AB+,Cancer,2022-09-19,Kathleen Hanna,White-White,Aetna,14238.317814,458,Urgent,2022-10-09,Penicillin,Abnormal

In [11]:
df['Age'].describe()

count    54966.000000
mean        51.535185
std         19.605661
min         13.000000
25%         35.000000
50%         52.000000
75%         68.000000
max         89.000000
Name: Age, dtype: float64

dari Informasi diatas: 
* **rata-rata** usia pasien ada di umur **51 tahun**
* usia **paling muda** pasien ada di umur **13 tahun**
* usia **paling tua** pasien ada di umur **89 tahun**

In [12]:
df['Gender'].value_counts()

Gender
Male      27496
Female    27470
Name: count, dtype: int64

dari informasi yang di dapatkan pasien laki-laki **lebih banyak (26 pasien)** dari pasien perempuan

In [13]:
df['Medical Condition'].value_counts()

Medical Condition
Arthritis       9218
Diabetes        9216
Hypertension    9151
Obesity         9146
Cancer          9140
Asthma          9095
Name: count, dtype: int64

dari informasi diatas di dapatkan penyakit yang **paling sering muncul** adalah **Arthritis** dengan total **9.218 pasien**, disusul penyakit **Diabetes** dan **Hypertension** untuk **top 3** penyakit yang paling sering muncul

In [14]:
df['Hospital'].nunique()

39876

Perintah **df['Hospital'].nunique()** untuk menghitung ada berapa banyak hospital yang tersedia pada dataset

In [15]:
df['Doctor'].nunique()

40341

Perintah **df['Doctor'].nunique()** untuk menghitung ada berapa banyak doctor yang tersedia pada dataset

In [16]:
df['Insurance Provider'].value_counts()

Insurance Provider
Cigna               11139
Medicare            11039
UnitedHealthcare    11014
Blue Cross          10952
Aetna               10822
Name: count, dtype: int64

dari informasi diatas didapatkan **top Insurance provider** adalah Cigna dengan total **11.139 pengguna**

In [17]:
df['Doctor'].value_counts()

Doctor
Michael Smith        27
John Smith           22
Robert Smith         21
James Smith          20
Michael Johnson      20
                     ..
Ashley Patton DDS     1
Wanda Stark           1
Tiffany Gibson        1
Christy Klein         1
Jeffery Christian     1
Name: count, Length: 40341, dtype: int64

dari Informasi diatas merupakan jumlah pasien perdokter, dokter yang **Handle paling banyak pasien** adalah **Doctor Michael Smith** sebanyak **27 Pasien**

In [18]:
df['Medication'].value_counts().head(10)

Medication
Lipitor        11038
Ibuprofen      11023
Aspirin        10984
Paracetamol    10965
Penicillin     10956
Name: count, dtype: int64

dari informasi diatas di dapatkan **top medication** adalah **Lipitor** sebanyak **11.038**

In [19]:
df['Date of Admission'] = pd.to_datetime(df['Date of Admission'])
df['Discharge Date'] = pd.to_datetime(df['Discharge Date'])

Perintah diatas untuk **mengubah data type** tanggal yang awalnya **object** menjadi **datetime**

In [24]:
df['Length of Stay'] = (df['Discharge Date'] - df['Date of Admission']).dt.days

Perintah diatas merupakan perintah membuat **kolom lama rawat inap pasien** di rumah sakit

In [26]:
df['Month'] = df['Date of Admission'].dt.month_name()

In [27]:
df['Year'] = df['Date of Admission'].dt.year

Perintah diatas merupakan perintah **membuat kolom Month dan Year** sebagai bahan untuk analisis

In [28]:
df.to_csv('clean_healthcare_dashboard.csv', index=False)